variables:
    DOCKER_TLS_CERTDIR: ""
    CONTAINER_IMAGE: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}
    # Required for docker:dind compatibility on shared runners.
    DOCKER_API_VERSION: "1.43"

stages:
  - build


# Template to build to docker image
.build:
  stage: build
  image: docker
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t ${CONTAINER_IMAGE} --no-cache .
    - docker push ${CONTAINER_IMAGE}
    - docker rmi ${CONTAINER_IMAGE}
    - docker logout $CI_REGISTRY


Docker-IMG:
  extends: 
    - .build
  variables:
    DOCKERFILE: Dockerfile
