variables:
    DOCKER_TLS_CERTDIR: ""
    CONTAINER_IMAGE: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}
    # Required for docker:dind compatibility on shared runners.
    DOCKER_API_VERSION: "1.43"
    DOCKER_IMAGE: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}
    BASE: k8s/base

stages:
  - build
  - deploy


# Template to build to docker image
.build:
  stage: build
  image: docker
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t ${CONTAINER_IMAGE} --no-cache .
    - docker push ${CONTAINER_IMAGE}
    - docker rmi ${CONTAINER_IMAGE}
    - docker logout $CI_REGISTRY


# Template to deploy application to k8s cluster
.deploy:
  stage: deploy
  image: dockerhub.ebi.ac.uk/${CI_PROJECT_NAMESPACE}/deploy-tools:latest

  before_script:
    - kubectl config use-context ${AGENT}

  script:
    - pwd
    - ls -la
    - cd ${BASE}
    - kustomize edit set image DOCKER_IMAGE=${DOCKER_IMAGE}
    - kustomize build . | kubectl apply -f -


build:
  extends: 
    - .build
  variables:
    DOCKERFILE: Dockerfile


Dev:
  extends: .deploy
  variables:
    BASE: k8s/overlays/dev
    AGENT: ${DEV_AGENT}
  environment:
    name: development
  when: manual

Staging:
  extends: .deploy
  variables:
    BASE: k8s/overlays/staging
    AGENT: ${STAGING_AGENT}
  environment:
    name: staging
  when: manual

Live:
  extends: .deploy
  variables:
    BASE: k8s/overlays/prod
    AGENT: ${PROD_AGENT}
  environment:
    name : production
  when: manual

Public:
  extends: .deploy
  variables:
    BASE: k8s/overlays/public-graphql
    AGENT: ${PUBLIC_AGENT}
  environment:
    name: public
  when: manual

# Live:Fallback:
#   extends: .deploy
#   variables:
#     BASE: k8s/overlays/prod
#     AGENT: ${FALLBACK_AGENT}
#   environment:
#     name : fallback
#   when: manual

# TODO: set the deployment to be manual (for now)