apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ensembl-prod
resources:
- ../../base
replacements:
- source:
    kind: ConfigMap
    name: refget-configmap
    fieldPath: data.REPLICA_NO
  targets:
  - select:
      kind: Deployment
      name: ensembl-refget-deployment
    fieldPaths:
    - spec.replicas
