apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ensembl-refget-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: www.ensembl.org
      http:
        paths:
          - path: /api/refget($|/)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: ensembl-refget-svc
                port:
                  number: 8000
