# We don't have any secrets for refget currently but this is here 
# as a placeholder for when we do and to show how to use them in 
# the deployment if needed. We can also use this for any future 
# environment variables that we want to keep secret and 
# not expose via configmaps.