apiVersion: v1
kind: Service
metadata:
  name: ensembl-refget-svc
  labels:
    app: ensembl-refget-svc
spec:
  type: ClusterIP
  selector:
    ensembl.web.api.name: ensembl-refget
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
